// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWtcoAyXYVvRqPjgvXzuBH9ANyy6t2o5Y',
    appId: '1:889247640827:web:248427fa2c3cb0d101d45e',
    messagingSenderId: '889247640827',
    projectId: 'flutterchat-764eb',
    authDomain: 'flutterchat-764eb.firebaseapp.com',
    storageBucket: 'flutterchat-764eb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzHbvzS3cceMkTXa7ZnP02VTJYk11FTbw',
    appId: '1:889247640827:android:5f908e72f6c44a7201d45e',
    messagingSenderId: '889247640827',
    projectId: 'flutterchat-764eb',
    storageBucket: 'flutterchat-764eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoERvieO_b2WmSr_e78946Rm6Y0aOqoyI',
    appId: '1:889247640827:ios:3454d1ce49a1f93101d45e',
    messagingSenderId: '889247640827',
    projectId: 'flutterchat-764eb',
    storageBucket: 'flutterchat-764eb.firebasestorage.app',
    iosBundleId: 'com.example.chattingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoERvieO_b2WmSr_e78946Rm6Y0aOqoyI',
    appId: '1:889247640827:ios:3454d1ce49a1f93101d45e',
    messagingSenderId: '889247640827',
    projectId: 'flutterchat-764eb',
    storageBucket: 'flutterchat-764eb.firebasestorage.app',
    iosBundleId: 'com.example.chattingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWtcoAyXYVvRqPjgvXzuBH9ANyy6t2o5Y',
    appId: '1:889247640827:web:08108a5274a8ef5a01d45e',
    messagingSenderId: '889247640827',
    projectId: 'flutterchat-764eb',
    authDomain: 'flutterchat-764eb.firebaseapp.com',
    storageBucket: 'flutterchat-764eb.firebasestorage.app',
  );
}
